[package]
name = "rust-bwt"
version = "0.1.0"
authors = ["nschwarz <noah.anabiik.schwarz@gmail.com>"]
edition = "2018"

[dependencies]
# lazy_static = "1.4.0"
serde_json = "1.0.40"
base64 = "0.10.1"
num_enum = "0.4.1"
# failure = "0.1.5"
