[package]
name = "rust-bwt"
version = "0.1.0"
authors = ["nschwarz <noah.anabiik.schwarz@gmail.com>"]
edition = "2018"

[dependencies]
chacha20-poly1305-aead = "0.1.2"
curve25519-dalek = "1.2.3"
lazy_static = "1.4.0"
serde_json = "1.0.40"
